Repository CSC207-2022F-UofT/course-project-team-bbq, pull requests merged in 2022-11, with the labels that each got.

#26 5 feature 6 study mode
  src/main/java/studyMode/FlashcardAlphComparator.java
  src/main/java/studyMode/FlashcardByDateComparator.java
  src/main/java/studyMode/FlashcardStudier.java
  src/main/java/studyMode/FlashcardStudierBuilder.java
  src/main/java/studyMode/FlashcardStudierFactory.java
  src/main/java/studyMode/MockMain.java
  src/main/java/studyMode/MockSettingsView.java
  src/main/java/studyMode/MockStudyView.java
  src/main/java/studyMode/StudySessionController.java
  src/main/java/studyMode/StudySessionInputBoundary.java
  src/main/java/studyMode/StudySessionInteractor.java
  src/main/java/studyMode/StudySessionOutputBoundary.java
  src/main/java/studyMode/StudySessionPresenter.java
  src/main/java/studyMode/StudySessionRequestModel.java
  src/main/java/studyMode/StudySessionResponseModel.java
  src/main/java/studyMode/StudySessionScreen.java
  src/main/java/studyMode/StudySettingsFailureScreen.java
  src/main/java/studyMode/StudySettingsRequestModel.java
  src/main/java/studyMode/StudySettingsResponseModel.java
  src/main/java/studyMode/StudySettingsScreen.java
Labels: enhancement

#43 Functional Quiz Mode
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradlew
  src/images/no.png
  src/images/spungebub.png
  src/images/yes.png
  src/main/java/Main.java
  src/main/java/QuizService.java
  src/main/java/dataAccess/DBGateway.java
  src/main/java/entities/Flashcard.java
  src/main/java/entities/MultipleChoiceQuestion.java
  src/main/java/entities/Quiz.java
  src/main/java/entities/QuizQuestion.java
  src/main/java/entities/QuizQuestionFactory.java
  src/main/java/entities/QuizSettings.java
  src/main/java/entities/TextEntryQuestion.java
  src/main/java/entities/TrueFalseQuestion.java
  src/main/java/quizUseCase/GUI/FlatLabel.java
  src/main/java/quizUseCase/GUI/MultipleChoiceQuestionCard.java
  src/main/java/quizUseCase/GUI/QuestionCard.java
  src/main/java/quizUseCase/GUI/Slider.java
  src/main/java/quizUseCase/GUI/TextEntryQuestionCard.java
  src/main/java/quizUseCase/GUI/TrueFalseQuestionCard.java
  src/main/java/quizUseCase/QuizBuilder.java
  src/main/java/quizUseCase/QuizController.java
  src/main/java/quizUseCase/QuizInputBoundary.java
  src/main/java/quizUseCase/QuizInteractor.java
  src/main/java/quizUseCase/QuizOutputBoundary.java
  src/main/java/quizUseCase/QuizPresenter.java
  src/main/java/quizUseCase/QuizRequestModel.java
  src/main/java/quizUseCase/QuizResponseModel.java
  src/main/java/quizUseCase/QuizSettingsRequestModel.java
  src/main/java/quizUseCase/QuizSettingsResponseModel.java
  src/main/java/quizUseCase/screens/QuizResultsScreen.java
  src/main/java/quizUseCase/screens/QuizScreen.java
  src/main/java/quizUseCase/screens/QuizSettingsScreen.java
  src/main/java/quizUseCase/screens/Screen.java
  src/main/java/studyMode/MockMain.java
Labels: enhancement

#50 [Ready to Merge] Features create and delete flashcard set
  src/main/java/create_flashcardset_use_case/CreationScreen.java
  src/main/java/create_flashcardset_use_case/FlashcardSetController.java
  src/main/java/create_flashcardset_use_case/FlashcardSetCreationFailed.java
  src/main/java/create_flashcardset_use_case/FlashcardSetInputBoundary.java
  src/main/java/create_flashcardset_use_case/FlashcardSetInteractor.java
  src/main/java/create_flashcardset_use_case/FlashcardSetOutputBoundary.java
  src/main/java/create_flashcardset_use_case/FlashcardSetPresenter.java
  src/main/java/create_flashcardset_use_case/FlashcardSetRequestModel.java
  src/main/java/create_flashcardset_use_case/FlashcardSetResponseModel.java
  src/main/java/create_flashcardset_use_case/InMemoryFlashcardSet.java
  src/main/java/create_flashcardset_use_case/LabelTextPanel.java
  src/main/java/create_flashcardset_use_case/MainCreateFlashcardSet.java
  src/main/java/dataAccess/FlashcardSetDataAccess.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetController.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetInputBoundary.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetInteractor.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetOutputBoundary.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetPresenter.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetRequestModel.java
  src/main/java/delete_flashcardset_use_case/DelFlashcardSetResponseModel.java
  src/main/java/delete_flashcardset_use_case/DeletionScreen.java
  src/main/java/delete_flashcardset_use_case/FlashcardSetNotFound.java
  src/main/java/delete_flashcardset_use_case/InMemoryFlashcard.java
  src/main/java/delete_flashcardset_use_case/MainDeleteFlashcardSet.java
  src/test/java/create_flashcardset_use_case/FlashcardSetInteractorTest.java
  src/test/java/delete_flashcardset_use_case/DelFlashcardSetInteractorTest.java
Labels: enhancement

#32 Feature 4 editing flashcard set
  .idea/misc.xml
  src/data/Flashcards.csv
  src/main/java/Editor/Flashcard/FlashcardEditorInputBoundary.java
  src/main/java/Editor/Flashcard/FlashcardEditorInteractor.java
  src/main/java/Editor/Flashcard/FlashcardEditorMain.java
  src/main/java/Editor/Flashcard/FlashcardEditorOutputBoundary.java
  src/main/java/Editor/Flashcard/FlashcardEditorRequestModel.java
  src/main/java/Editor/Flashcard/FlashcardEditorResponseModel.java
  src/main/java/Editor/Flashcard/screens/FlashcardEditFailed.java
  src/main/java/Editor/Flashcard/screens/FlashcardEditorController.java
  src/main/java/Editor/Flashcard/screens/FlashcardEditorPresenter.java
  src/main/java/Editor/Flashcard/screens/FlashcardEditorScreen.java
  src/main/java/Editor/Flashcard/screens/InMemoryFlashcard.java
  src/main/java/Editor/FlashcardSet/FCSetEditorInputBoundary.java
  src/main/java/Editor/FlashcardSet/FCSetEditorInteractor.java
  src/main/java/Editor/FlashcardSet/FCSetEditorMain.java
  src/main/java/Editor/FlashcardSet/FCSetEditorOutputBoundary.java
  src/main/java/Editor/FlashcardSet/FCSetEditorRequestModel.java
  src/main/java/Editor/FlashcardSet/FCSetEditorResponseModel.java
  src/main/java/Editor/FlashcardSet/screens/FCSetEditFailed.java
  src/main/java/Editor/FlashcardSet/screens/FCSetEditorController.java
  src/main/java/Editor/FlashcardSet/screens/FCSetEditorPresenter.java
  src/main/java/Editor/FlashcardSet/screens/FCSetEditorScreen.java
  src/main/java/Editor/FlashcardSet/screens/InMemoryFlashcardSet.java
  src/main/java/Editor/Test/FCSetEditorInteractorTest.java
  src/main/java/Editor/Test/FlashcardInteractorTest.java
  src/main/java/dataAccess/IGeneralDataAccess.java
Labels: enhancement

#58 added save and delete flashcard / flashcardset methods to DBGateway. …
  src/main/java/dataAccess/CommonUserDataAccess.java
  src/main/java/dataAccess/DBGateway.java
  src/main/java/dataAccess/IUserDataAccess.java
Labels: help wanted

#61 8 feature main home page
  src/data/FlashcardSets.csv
  src/data/Users.csv
  src/main/java/EditorMainPage/EditorMainPage.java
  src/main/java/EditorMainPage/ListOfFlashcardsDataPanel.java
  src/main/java/Main.java
  src/main/java/MainPage/FlashcardSetDataPanel.java
  src/main/java/MainPage/HomePage.java
  src/main/java/MainPage/ListOfFlashcardSetsDataPanel.java
  src/main/java/create_flashcardset_use_case/CreationScreen.java
  src/main/java/create_flashcardset_use_case/MainCreateFlashcardSet.java
  src/main/java/dataAccess/CommonUserDataAccess.java
  src/main/java/dataAccess/DBGateway.java
  src/main/java/delete_flashcardset_use_case/DeletionScreen.java
  src/main/java/delete_flashcardset_use_case/MainDeleteFlashcardSet.java
  src/main/java/loginAndSignupUseCase/UserLoginInteractor.java
  src/main/java/loginAndSignupUseCase/UserLoginResponseModel.java
  src/main/java/loginAndSignupUseCase/UserRegisterInteractor.java
  src/main/java/loginAndSignupUseCase/loginAndSignupUseCaseScreens/LoginScreen.java
  src/main/java/loginAndSignupUseCase/loginAndSignupUseCaseScreens/RegisterScreen.java
  src/main/java/loginAndSignupUseCase/loginAndSignupUseCaseScreens/WelcomeScreen.java
  src/main/java/quizUseCase/screens/Screen.java
  src/main/java/searchTestMain.java
  src/main/java/search_use_case/SearchRequestModel.java
  src/main/java/search_use_case/SearchScreen.java
  src/main/java/studyMode/screens/StudySessionScreen.java
  src/main/java/studyMode/screens/StudySettingsScreen.java
Labels: help wanted

#85 Implemented refresh on home page
  .idea/misc.xml
  src/main/java/editor_main_page/FlashcardDataPanel.java
  src/main/java/login_and_signup_use_case/UserLoginInteractor.java
  src/main/java/login_and_signup_use_case/UserLoginResponseModel.java
  src/main/java/login_and_signup_use_case/login_and_signup_use_case_screens/LoginScreen.java
  src/main/java/login_and_signup_use_case/login_and_signup_use_case_screens/RegisterScreen.java
  src/main/java/login_and_signup_use_case/login_and_signup_use_case_screens/UserLoginController.java
  src/main/java/main_page/FlashcardSetDataPanel.java
  src/main/java/main_page/HomePage.java
  src/main/java/main_page/ListOfFlashcardSetsDataPanel.java
  src/test/java/search_use_case/SearchUseCaseTest.java
Labels: enhancement

#88 Added Javadocs for features create and delete flashcard sets
  src/main/java/create_flashcard_set_use_case/FlashcardSetController.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetCreationFailed.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetInputBoundary.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetInteractor.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetOutputBoundary.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetPresenter.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetRequestModel.java
  src/main/java/create_flashcard_set_use_case/FlashcardSetResponseModel.java
  src/main/java/create_flashcard_set_use_case/InMemoryFlashcardSet.java
  src/main/java/create_flashcard_set_use_case/LabelTextPanel.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetController.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetInputBoundary.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetInteractor.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetOutputBoundary.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetPresenter.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetRequestModel.java
  src/main/java/delete_flashcard_set_use_case/DelFlashcardSetResponseModel.java
  src/main/java/delete_flashcard_set_use_case/FlashcardSetNotFound.java
  src/main/java/delete_flashcard_set_use_case/InMemoryFlashcard.java
Labels: documentation
