Repository CSC207-2022F-UofT/course-project-team-bbq, pull requests merged in 2022-12, with the labels that each got.

#91 Added documentation of my use cases to the README file
  README.md
Labels: documentation

#92 Resolve the problem of creating duplicate flashcards with the same term.
  src/main/java/create_flashcard_use_case/CreateFlashcardInputBoundary.java
  src/main/java/create_flashcard_use_case/CreateFlashcardInteractor.java
  src/main/java/create_flashcard_use_case/CreateFlashcardOutputBoundary.java
  src/main/java/create_flashcard_use_case/CreateFlashcardRequestModel.java
  src/main/java/create_flashcard_use_case/CreateFlashcardResponseModel.java
  src/main/java/delete_flashcard_use_case/DeleteFlashcardInteractor.java
  src/main/java/frameworks_and_drivers/components/CreateFlashcardPanel.java
  src/main/java/frameworks_and_drivers/components/DeleteFlashcardPanel.java
  src/main/java/frameworks_and_drivers/screens/DeleteFlashcardScreen.java
  src/main/java/interface_adapters/controllers/CreateFlashcardController.java
  src/main/java/interface_adapters/controllers/DeleteFlashcardController.java
  src/main/java/interface_adapters/presenters/CreateFlashcardPresenter.java
  src/test/java/create_flashcard_use_case/FcCInteractorTest.java
  src/test/java/delete_flashcard_use_case/FcRInteractorTest.java
Labels: bug, documentation

#96 Feature edit main page WindowListener Bug fix
  src/data/Flashcards.csv
  src/main/java/edit_flashcard_use_case/function_testing/InMemoryFlashcard.java
  src/main/java/frameworks_and_drivers/components/FlashcardDataPanel.java
  src/main/java/frameworks_and_drivers/components/FlashcardSetDataPanel.java
  src/main/java/frameworks_and_drivers/components/ListOfFlashcardSetsDataPanel.java
  src/main/java/frameworks_and_drivers/components/ListOfFlashcardsDataPanel.java
  src/main/java/frameworks_and_drivers/screens/EditorMainScreen.java
  src/main/java/frameworks_and_drivers/screens/HomeScreen.java
  src/test/java/edit_flashcard_use_case/FlashcardInteractorTest.java
Labels: bug

#104 Feature 5 flashcard creator and remover Added delete flashcard confirmation screen.
  README.md
  src/main/java/create_flashcard_use_case/CreateFlashcardInputBoundary.java
  src/main/java/create_flashcard_use_case/CreateFlashcardInteractor.java
  src/main/java/create_flashcard_use_case/function_testing/InMemoryFlashcard.java
  src/main/java/create_flashcard_use_case/function_testing/InMemoryFlashcardSet.java
  src/main/java/frameworks_and_drivers/components/CreateFlashcardPanel.java
  src/main/java/frameworks_and_drivers/components/DeleteFlashcardPanel.java
  src/main/java/frameworks_and_drivers/screens/CreateFlashcardScreen.java
  src/main/java/frameworks_and_drivers/screens/DeleteFlashcardScreen.java
Labels: documentation
